# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('author', models.CharField(max_length=101, null=True)),
                ('number_pages', models.IntegerField(null=True)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=15)),
                ('url', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklos.categories'),
        ),
    ]
