# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
