# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='url',
        ),
    ]
