# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0002_remove_books_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='url',
            field=models.TextField(default='fd'),
            preserve_default=False,
        ),
    ]
