# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0004_remove_books_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
    ]
