# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0005_books_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
