# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0005_remove_books_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='publisher',
        ),
    ]
