# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0006_remove_books_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=101, null=True),
        ),
    ]
