# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0007_auto_20160530_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='number_pages',
            field=models.IntegerField(null=True),
        ),
    ]
