# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0008_auto_20160530_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
