# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0008_auto_20160609_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booklos.categories'),
        ),
    ]
