# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0009_auto_20160609_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('category',)},
        ),
        migrations.AddField(
            model_name='categories',
            name='category_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
