# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 04:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0009_auto_20160531_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 31, 4, 16, 15, 466879, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 31, 4, 16, 28, 818955, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 5, 31, 4, 17, 9, 437461, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
