# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0010_auto_20160610_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='number_pages',
        ),
        migrations.RemoveField(
            model_name='books',
            name='publisher',
        ),
    ]
