# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0011_auto_20160531_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
