# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 02:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0012_auto_20160531_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.CharField(default=datetime.datetime(2016, 6, 2, 2, 23, 29, 486844, tzinfo=utc), max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='reviews',
            field=models.TextField(default=datetime.datetime(2016, 6, 2, 2, 23, 41, 141730, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='url',
            field=models.TextField(default=datetime.datetime(2016, 6, 2, 2, 23, 47, 250217, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
