# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklos', '0013_auto_20160602_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='updated',
        ),
    ]
